const master_prompts = [
    "If you could have dinner with any historical figure, who would it be?",
    "What's your favorite travel destination?",
    "If you could only eat one cuisine for the rest of your life, what would it be?",
    "What's a skill you've always wanted to learn?",
    "What's the best piece of advice you've ever received?",
    "If you could live in any fictional universe, where would you choose?",
    "What's your go-to karaoke song?",
    "What's your favorite book?",
    "If you could time travel, would you go to the past or the future?",
    "What's your favorite way to relax after a long day?",
    "What's something on your bucket list?",
    "If you could have any superpower, what would it be?",
    "What's your favorite season?",
    "If you could swap lives with anyone for a day, who would it be?",
    "What's the most adventurous thing you've ever done?",
    "What's your favorite childhood memory?",
    "If you could only watch one movie for the rest of your life, what would it be?",
    "What's your guilty pleasure?",
    "What's the best concert you've ever been to?",
    "What's a hobby you've always wanted to try?",
    "If you could have any job in the world, what would it be?",
    "What's your favorite thing about yourself?",
    "If you could change one thing about the world, what would it be?",
    "What's the most spontaneous thing you've ever done?",
    "What's your favorite thing to do on a rainy day?",
    "If you could have dinner with any fictional character, who would it be?",
    "What's a movie or TV show you could watch over and over again?",
    "What's your favorite type of cuisine to cook at home?",
    "If you could visit any country in the world, where would you go?",
    "What's the most interesting place you've ever visited?",
    "What's your favorite holiday?",
    "If you could have any animal as a pet, what would it be?",
    "What's your favorite board game or card game?",
    "If you could meet any celebrity, who would you choose?",
    "What's something you've always wanted to do but haven't done yet?",
    "What's your favorite thing to do on a lazy Sunday?",
    "What's your favorite type of music?",
    "If you could have any talent, what would it be?",
    "What's your favorite way to spend time with friends?",
    "What's your favorite childhood movie?",
    "If you could be any fictional character, who would you be?",
    "What's your favorite dessert?",
    "What's the best piece of advice you would give to your younger self?",
    "What's the most interesting job you've ever had?",
    "If you could live in any time period, when would you choose?",
    "What's your favorite thing to do in your free time?",
    "If you could have any car, what would it be?",
    "What's your favorite way to exercise?",
    "If you could have any meal right now, what would it be?",
    "What's your favorite quote?",
    "What's something you're passionate about?",
    "If you could have any hobby, what would it be?",
    "What's your favorite thing about where you live?",
    "What's the best advice you've ever received about relationships?",
    "If you could change one thing about yourself, what would it be?",
    "What's your favorite thing to do outdoors?",
    "If you could have any job for a day, what would it be?",
    "What's your favorite way to spend a Friday night?",
    "If you could have any pet in the world, what would it be?",
    "What's your favorite TV show?",
    "What's your favorite thing to do in the summer?",
    "If you could have any superpower, what would it be?",
    "What's the most memorable gift you've ever received?",
    "What's your favorite thing about your best friend?",
    "If you could travel back in time, what era would you visit?",
    "What's your favorite thing to do in the fall?",
    "If you could have any talent, what would it be?",
    "What's your favorite thing about winter?",
    "If you could only eat one food for the rest of your life, what would it be?",
    "What's your favorite thing to do in the spring?",
    "If you could have any job in the world, what would it be?",
    "What's the most interesting thing you've learned recently?",
    "What's your favorite way to spend a Saturday?",
    "If you could have any animal as a pet, what would it be?",
    "What's your favorite thing about your family?",
    "If you could have any talent, what would it be?",
    "What's your favorite thing about yourself?",
    "What's the best advice you've ever received?",
    "If you could have any job in the world, what would it be?",
    "What's your favorite thing to do on a rainy day?",
    "If you could travel anywhere in the world, where would you go?",
    "What's your favorite movie?",
    "If you could have any superpower, what would it be?",
    "What's your favorite way to relax after a long day?",
    "If you could have dinner with any historical figure, who would it be?",
    "What's your favorite book?",
    "If you could live in any fictional universe, where would you live?",
    "What's your go-to karaoke song?",
    "If you could have any talent, what would it be?",
    "What's your favorite season?",
    "If you could swap lives with anyone for a day, who would it be?",
    "What's the most adventurous thing you've ever done?",
    "What's your favorite childhood memory?",
    "If you could only watch one movie for the rest of your life, what would it be?",
    "What's your guilty pleasure?",
    "What's the best concert you've ever been to?",
    "What's a hobby you've always wanted to try?",
    "If you could have any job in the world, what would it be?",
    "What's your favorite thing about yourself?",
    "If you could change one thing about the world, what would it be?",
    "What's the most spontaneous thing you've ever done?",
    "What's your favorite thing to do on a rainy day?",
    "If you could have dinner with any fictional character, who would it be?",
    "What's a movie or TV show you could watch over and over again?",
    "What's your favorite type of cuisine to cook at home?",
    "If you could visit any country in the world, where would you go?",
    "What's the most interesting place you've ever visited?",
    "What's your favorite holiday?",
    "If you could have any animal as a pet"
];

export {master_prompts};



